namespace MagicRealm.Resources.EnumeratedTypes
{
	public enum MagicRealmNativeGroupEnum
	{
		MAGIC_REALM_NATIVE_GROUP_BASHKARS, 
		MAGIC_REALM_NATIVE_GROUP_COMPANY, 
		MAGIC_REALM_NATIVE_GROUP_GUARD, 
		MAGIC_REALM_NATIVE_GROUP_LANCERS, 
		MAGIC_REALM_NATIVE_GROUP_ORDER, 
		MAGIC_REALM_NATIVE_GROUP_PATROL, 
		MAGIC_REALM_NATIVE_GROUP_ROGUES, 
		MAGIC_REALM_NATIVE_GROUP_SOLDIERS, 
		MAGIC_REALM_NATIVE_GROUP_WOODFOLK
	}
}
