namespace MagicRealm.Resources.EnumeratedTypes
{
	public enum MagicRealmRelationshipStatusEnum
	{
		MAGIC_REALM_RELATIONSHIP_STATUS_ALLY, 
		MAGIC_REALM_RELATIONSHIP_STATUS_FRIENDLY, 
		MAGIC_REALM_RELATIONSHIP_STATUS_UNFRIENDLY, 
		MAGIC_REALM_RELATIONSHIP_STATUS_ENEMY
	}
}
