namespace MagicRealm.Resources.EnumeratedTypes
{
	public enum MagicRealmMagicTypeEnum
	{
		MAGIC_REALM_MAGIC_TYPE_I, 
		MAGIC_REALM_MAGIC_TYPE_II, 
		MAGIC_REALM_MAGIC_TYPE_III, 
		MAGIC_REALM_MAGIC_TYPE_IV, 
		MAGIC_REALM_MAGIC_TYPE_V, 
		MAGIC_REALM_MAGIC_TYPE_VI, 
		MAGIC_REALM_MAGIC_TYPE_VII, 
		MAGIC_REALM_MAGIC_TYPE_VIII
	}
}
