namespace MagicRealm.Resources.EnumeratedTypes
{
	public enum MagicRealmSiteEnum
	{
		MAGIC_REALM_SITE_ALTAR, 
		MAGIC_REALM_SITE_CAIRNS, 
		MAGIC_REALM_SITE_HOARD, 
		MAGIC_REALM_SITE_LAIR, 
		MAGIC_REALM_SITE_LOST_CASTLE, 
		MAGIC_REALM_SITE_LOST_CITY, 
		MAGIC_REALM_SITE_POOL, 
		MAGIC_REALM_SITE_SHRINE, 
		MAGIC_REALM_SITE_STATUE, 
		MAGIC_REALM_SITE_VAULT
	}
}
