namespace MagicRealm.Resources.EnumeratedTypes
{
	public enum MagicRealmRoadwayTypeEnum
	{
		MAGIC_REALM_ROADWAY_TYPE_TUNNEL, 
		MAGIC_REALM_ROADWAY_TYPE_OPEN_ROAD, 
		MAGIC_REALM_ROADWAY_TYPE_HIDDEN_PATH, 
		MAGIC_REALM_ROADWAY_TYPE_SECRET_PASSAGE
	}
}
