namespace MagicRealm.Resources.EnumeratedTypes
{
	public enum MagicRealmCounterActionEnum
	{
		MAGIC_REALM_COUNTER_ACTION_BERSERK, 
		MAGIC_REALM_COUNTER_ACTION_DUCK, 
		MAGIC_REALM_COUNTER_ACTION_FIGHT, 
		MAGIC_REALM_COUNTER_ACTION_MOVE, 
		MAGIC_REALM_COUNTER_ACTION_MAGIC
	}
}
